branch-defaults:
  default:
    environment: chatbot-article-dev3
  master:
    environment: chatbot-article-env
environment-defaults:
  chatbot-article-dev3:
    branch: null
    repository: null
  chatbot-article-env:
    branch: master
    repository: eb_chatbot
global:
  application_name: chatbot_article
  default_ec2_keyname: chatbot_keypair
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.3
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
