# Generated by Django 2.0.1 on 2018-01-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summarized_title',
            new_name='summarized_text',
        ),
    ]
