# Generated by Django 2.0.1 on 2018-01-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180103_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summarized_text',
        ),
    ]
