# Generated by Django 2.0.1 on 2018-01-09 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0007_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsId', models.IntegerField(default=0)),
                ('press', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('summarized_text', models.TextField()),
                ('url', models.URLField(default='https://')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
