# Generated by Django 2.0.1 on 2018-01-09 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180109_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('crawled_date', models.DateTimeField()),
                ('recomm', models.IntegerField()),
                ('unrecomm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('press', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('link', models.URLField(default='https://')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='user_id',
            new_name='user_key',
        ),
        migrations.CreateModel(
            name='Document_summary',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='article.Document')),
                ('sentences_n', models.IntegerField()),
                ('text_rank', models.TextField()),
                ('top_word', models.TextField()),
                ('top_word_count', models.TextField()),
                ('top_word_tfidf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment_list',
            fields=[
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='article.Document')),
                ('good', models.IntegerField()),
                ('warm', models.IntegerField()),
                ('sad', models.IntegerField()),
                ('angry', models.IntegerField()),
                ('want', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='comment',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Document'),
        ),
    ]
