# Generated by Django 2.0.1 on 2018-01-10 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180110_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
