# Generated by Django 2.0.1 on 2018-01-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20180115_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-01-15 23:23'),
        ),
    ]
