# Generated by Django 2.0.1 on 2018-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20180115_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='request_date',
            field=models.DateTimeField(default='2018-01-17 09:13'),
        ),
    ]
