# Generated by Django 2.0.1 on 2018-01-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_summary',
            name='top_word',
        ),
    ]
